In [1]:
from steer_core.DataManager import DataManager
from steer_opencell_design import AnodeMaterial
from steer_materials import __version__

import pandas as pd

In [2]:
db = DataManager()

In [3]:
db.get_table_names()

[]

In [4]:
db.drop_table('anode_materials')

In [5]:
db.create_table(table_name='anode_materials', columns={
    'name': 'TEXT',
    'object': 'TEXT',
    'date': 'TEXT',
    'version': 'TEXT',
    'reference': 'TEXT'
})

In [6]:
# hc1

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/anode/Hard Carbon (Vendor A - 330 mAh g).csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

hc1 = AnodeMaterial(
    name = 'Hard Carbon (Vendor A)',
    reference = 'Na/Na+',
    specific_cost = 7.00,
    density = 1.5,
    specific_capacity_curves = half_cell,
    color='#1a1a1a'
)

hc1.plot_specific_capacity_curves(width=900, height=500).show()

In [7]:
# hc2

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/anode/Hard Carbon (Vendor B - 300 mAh g).csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

# px.line(half_cell, x='specific_capacity', y='voltage', markers=True, color='direction').show()

hc2 = AnodeMaterial(
    name = 'Hard Carbon (Vendor B)',
    reference = 'Na/Na+',
    specific_cost = 7.00,
    density = 1.5,
    specific_capacity_curves = half_cell,
    color='#1a1a1a'
)

hc2.plot_specific_capacity_curves(width=900, height=500).show()

In [8]:
# hc4

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/anode/Hard Carbon (Vendor D1 - 300 mAh g).csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

# px.line(half_cell, x='specific_capacity', y='voltage', markers=True, color='direction').show()

hc4 = AnodeMaterial(
    name = 'Hard Carbon (Vendor D)',
    reference = 'Na/Na+',
    specific_cost = 7.00,
    density = 1.5,
    specific_capacity_curves = half_cell,
    color='#1a1a1a'
)

hc4.plot_specific_capacity_curves(width=900, height=500).show()

In [9]:
# hc5

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/anode/Hard Carbon (Vendor D2 - 300 mAh g).csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

# px.line(half_cell, x='specific_capacity', y='voltage', markers=True, color='direction').show()

hc5 = AnodeMaterial(
    name = 'Hard Carbon (Vendor E)',
    reference = 'Na/Na+',
    specific_cost = 7.00,
    density = 1.5,
    specific_capacity_curves = half_cell,
    color='#1a1a1a'
)

hc5.plot_specific_capacity_curves(width=900, height=500).show()

In [10]:
# lead 

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/anode/lead.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

# px.line(half_cell, x='specific_capacity', y='voltage', markers=True, color='direction').show()

pb = AnodeMaterial(
    name = 'Lead',
    reference = 'Na/Na+',
    specific_cost = 2.50,
    density = 11.340,
    specific_capacity_curves = half_cell,
    color='#6e7f80'
)

pb.plot_specific_capacity_curves(width=900, height=500).show()

In [11]:
# Synthetic Graphite 

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/anode/Synthetic Graphite.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

# px.line(half_cell, x='specific_capacity', y='voltage', markers=True, color='direction').show()

sg = AnodeMaterial(
    name = 'Synthetic Graphite',
    reference = 'Li/Li+',
    specific_cost = 2.50,
    density = 11.340,
    specific_capacity_curves = half_cell,
    color='#6e7f80'
)

sg.plot_specific_capacity_curves(width=900, height=500).show()

In [12]:
# Synthetic Graphite 

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/anode/Tin.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

# px.line(half_cell, x='specific_capacity', y='voltage', markers=True, color='direction').show()

tn = AnodeMaterial(
    name = 'Tin',
    reference = 'Na/Na+',
    specific_cost = 2.50,
    density = 11.340,
    specific_capacity_curves = half_cell,
    color='#6e7f80'
)

tn.plot_specific_capacity_curves(width=900, height=500).show()

In [13]:
materials = [
    hc1, hc2, hc4, hc5, pb, sg, tn
]

pickled_materials = [m.serialize() for m in materials]

In [14]:

db.insert_data(table_name='anode_materials', data=pd.DataFrame({
    'name': [m.name for m in materials],
    'object': pickled_materials,
    'date': [m.last_updated for m in materials],
    'version': [__version__ for m in materials],
    'reference': [m.reference for m in materials]
}))

In [15]:
db.get_anode_materials(most_recent=False)

,name,object,date,version,reference
0,Hard Carbon (Vendor A),gASV4iMAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:29,0.1.16,Na/Na+
1,Hard Carbon (Vendor B),gASVAhkAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+
2,Hard Carbon (Vendor D),gASVgiYAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+
3,Hard Carbon (Vendor E),gASVwiUAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+
4,Lead,gASVYBsAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+
5,Synthetic Graphite,gASVPQIAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Li/Li+
6,Tin,gASVfy4AAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+

In [16]:
db.get_anode_materials(most_recent=True)

,name,object,date,version,reference
0,Hard Carbon (Vendor A),gASV4iMAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:29,0.1.16,Na/Na+
1,Hard Carbon (Vendor B),gASVAhkAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+
2,Hard Carbon (Vendor D),gASVgiYAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+
3,Hard Carbon (Vendor E),gASVwiUAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+
4,Lead,gASVYBsAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+
5,Synthetic Graphite,gASVPQIAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Li/Li+
6,Tin,gASVfy4AAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:30,0.1.16,Na/Na+