In [ ]:
from steer_core.Data.DataManager import DataManager
from steer_opencell_design import Binder
from steer_materials import __version__
import pandas as pd

In [2]:
db = DataManager()

In [3]:
db.get_table_names()

['binder_materials',
 'cathode_materials',
 'conductive_additive_materials',
 'current_collector_materials',
 'insulation_materials',
 'prismatic_container_materials',
 'separator_materials',
 'tape_materials',
 'anode_materials']

In [4]:
db.drop_table('binder_materials')

In [5]:
db.create_table(table_name='binder_materials', columns={
    'name': 'TEXT',
    'object': 'TEXT',
    'date': 'TEXT',
    'version': 'TEXT'
})

In [6]:
# materials 

pvdf = Binder(name='PVDF', density=1.78, specific_cost=12, color='#e5e5e5')
sbr = Binder(name='SBR', density=0.94, specific_cost=1, color='#f4e3d7')
cmc = Binder(name='CMC', density=1.6, specific_cost=3, color='#d6cfc7')
paa = Binder(name='PAA', density=1.22, specific_cost=3, color='#e4dada')
alg = Binder(name='Alginate', density=1.6, specific_cost=2, color='#c2b280')

materials = [pvdf, sbr, cmc, paa, alg]

pickled_materials = [m.serialize() for m in materials]

In [7]:
# store data for current collectors

db.insert_data(table_name='binder_materials', data=pd.DataFrame({
    'name': [m.name for m in materials],
    'object': pickled_materials,
    'date': [m.last_updated for m in materials],
    'version': [__version__ for m in materials],
}))

In [8]:
db.get_binder_materials(most_recent=False)

,name,object,date,version
0,PVDF,"b""\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xdaa\...",2025-12-13 13:39:36,0.1.17
1,SBR,b'\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xda\x...,2025-12-13 13:39:36,0.1.17
2,CMC,b'\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xdaa\...,2025-12-13 13:39:36,0.1.17
3,PAA,b'\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xdaa2...,2025-12-13 13:39:36,0.1.17
4,Alginate,b'\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xdaa\...,2025-12-13 13:39:36,0.1.17

In [9]:
db.get_binder_materials()

,name,object,date,version
0,PVDF,"b""\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xdaa\...",2025-12-13 13:39:36,0.1.17
1,SBR,b'\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xda\x...,2025-12-13 13:39:36,0.1.17
2,CMC,b'\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xdaa\...,2025-12-13 13:39:36,0.1.17
3,PAA,b'\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xdaa2...,2025-12-13 13:39:36,0.1.17
4,Alginate,b'\x01x\x9c\xebZ\x11\x9f\x92\x9aW\x9cYRy\xdaa\...,2025-12-13 13:39:36,0.1.17

In [10]:
binder = Binder.from_database('PVDF')

ModuleNotFoundError: No module named 'steer_core.DataManager'