In [1]:
from steer_core.DataManager import DataManager
from steer_opencell_design import CathodeMaterial
from steer_materials import __version__
import pandas as pd

In [2]:
db = DataManager()

In [3]:
db.get_table_names()

['cells',
 'conductive_additive_materials',
 'current_collector_materials',
 'insulation_materials',
 'prismatic_container_materials',
 'separator_materials',
 'tape_materials',
 'anode_materials',
 'binder_materials',
 'cathode_materials']

In [4]:
db.drop_table('cathode_materials')

In [5]:
db.create_table(table_name='cathode_materials', columns={
    'name': 'TEXT',
    'object': 'TEXT',
    'date': 'TEXT',
    'version': 'TEXT',
    'reference': 'TEXT'
})

In [6]:
# LFP

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/LFP.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

lfp = CathodeMaterial(
    name = 'LFP',
    reference = 'Li/Li+',
    specific_cost = 6.00,
    density = 3.6,
    specific_capacity_curves = half_cell,
    color='#2c2c2c'
)

lfp.plot_specific_capacity_curves(width=900, height=500).show()

In [7]:
# NNM

csv1 = '../local_data/active_materials/cathode/NaNiMn P2-O3 Composite - 4.1V.csv'
csv2 = '../local_data/active_materials/cathode/NaNiMn P2-O3 Composite - 4.25V.csv'
csv3 = '../local_data/active_materials/cathode/NaNiMn P2-O3 Composite - 4.35V.csv'

half_cells = []
for csv in [csv1, csv2, csv3]:

    half_cell = (
        pd.read_csv(
            csv,
            names=['specific_capacity', 'voltage', 'direction', 'id'],
            skiprows=1
        ).drop(
            columns=['id']
        ).assign(
            direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
        )
    )

    half_cells.append(half_cell)

nnm = CathodeMaterial(
    name = 'NaNiMn P2-O3 Composite',
    reference = 'Na/Na+',
    specific_cost = 11.00,
    density = 4.4,
    specific_capacity_curves = half_cells,
    color='#1f1f1f'
)

nnm.plot_specific_capacity_curves(width=900, height=500).show()

In [8]:
# NFM vendor 1

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/NFM111 (Vendor A).csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

nfm1 = CathodeMaterial(
    name = 'NFM111 (Vendor A)',
    reference = 'Na/Na+',
    specific_cost = 11.00,
    density = 4.25,
    specific_capacity_curves = half_cell,
    color='#2b1f1a'
)

nfm1.plot_specific_capacity_curves(width=900, height=500).show()

In [9]:
# NFM vendor 2

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/NFM111 (Vendor B).csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

nfm2 = CathodeMaterial(
    name = 'NFM111 (Vendor B)',
    reference = 'Na/Na+',
    specific_cost = 11.00,
    density = 4.25,
    specific_capacity_curves = half_cell,
    color='#2b1f1a'
)

nfm2.plot_specific_capacity_curves(width=900, height=500).show()

In [10]:
# NFM Vendor 3

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/NFM111 (Vendor C).csv',
        names=['time', 'voltage', 'capacity', 'id', 'discharge_charge', 'charge_charge'],
        # names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).assign(
        direction = lambda x: x['id'].apply(lambda y: 'charge' if y == 0 else 'discharge')
    ).assign(
        specific_capacity = lambda x: x['capacity'] / (3.786e-3),
        direction = lambda x: x['time'].apply(lambda y: 'charge' if y < 25545.76 else 'discharge'),
    ).drop(
        columns=['id', 'charge_charge', 'discharge_charge', 'capacity']
    )
)

nfm3 = CathodeMaterial(
    name = 'NFM111 (Vendor C)',
    reference = 'Na/Na+',
    specific_cost = 11.00,
    density = 4.25,
    specific_capacity_curves = half_cell,
    color='#2b1f1a'
)

nfm3.plot_specific_capacity_curves(width=900, height=500).show()

In [11]:
# NFPP

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/NFPP.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

nfpp = CathodeMaterial(
    name = 'NFPP',
    reference = 'Na/Na+',
    specific_cost = 11.00,
    density = 2.95,
    specific_capacity_curves = half_cell,
    color='#7b3f00'
)

nfpp.plot_specific_capacity_curves(width=900, height=500).show()

In [12]:
# NMC622

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/NMC622.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

nmc622 = CathodeMaterial(
    name = 'NMC622',
    reference = 'Li/Li+',
    specific_cost = 22.00,
    density = 4.75,
    specific_capacity_curves = half_cell,
    color='#9daaa2'
)

nmc622.plot_specific_capacity_curves(width=900, height=500).show()

In [13]:
# NMC811

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/NMC811.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

nmc811 = CathodeMaterial(
    name = 'NMC811',
    reference = 'Li/Li+',
    specific_cost = 25.00,
    density = 4.8,
    specific_capacity_curves = half_cell,
    color='#7f8f87'
)

nmc811.plot_specific_capacity_curves(width=900, height=500).show()

In [14]:
# NVP

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/NVP.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

nvp = CathodeMaterial(
    name = 'NVP',
    reference = 'Na/Na+',
    specific_cost = 20.00,
    density = 3.2,
    specific_capacity_curves = half_cell,
    color='#c2b280'
)

nvp.plot_specific_capacity_curves(
    width=900, 
    height=500
).show()

In [15]:
# NVPF

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/NVPF.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

nvpf = CathodeMaterial(
    name = 'NVPF',
    reference = 'Na/Na+',
    specific_cost = 20.00,
    density = 3.3,
    specific_capacity_curves = half_cell,
    color="#7f7f7f"
)

nvpf.plot_specific_capacity_curves(width=900, height=500).show()

In [16]:
# Prussian White

half_cell = (
    pd.read_csv(
        '../local_data/active_materials/cathode/Prussian White.csv',
        names=['specific_capacity', 'voltage', 'direction', 'id'],
        skiprows=1
    ).drop(
        columns=['id']
    ).assign(
        direction = lambda x: x['direction'].apply(lambda y: 'discharge' if y == 'CC_DChg' else 'charge'),
    )
)

pw = CathodeMaterial(
    name = 'Prussian White',
    reference = 'Na/Na+',
    specific_cost = 15.00,
    density = 2.0,
    specific_capacity_curves = half_cell,
    color="#83bffb"   
)

pw.plot_specific_capacity_curves(width=900, height=500).show()

In [17]:
materials = [
    lfp,
    nnm,
    nfm1,
    nfm2,
    nfm3,
    nfpp,
    nmc622,
    nmc811,
    nvp,
    nvpf,
    pw
]

pickled_materials = [m.serialize() for m in materials]

In [18]:

db.insert_data(table_name='cathode_materials', data=pd.DataFrame({
    'name': [m.name for m in materials],
    'object': pickled_materials,
    'date': [m.last_updated for m in materials],
    'version': [__version__ for m in materials],
    'reference': [m.reference for m in materials]
}))

In [19]:
db.get_cathode_materials(most_recent=False)

,name,object,date,version,reference
0,LFP,gASVURYAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Li/Li+
1,NaNiMn P2-O3 Composite,gASVay8AAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
2,NFM111 (Vendor A),gASVHyYAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
3,NFM111 (Vendor B),gASVLyIAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
4,NFM111 (Vendor C),gASVPgIAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
5,NFPP,gASVgi4AAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
6,NMC622,gASV9B4AAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Li/Li+
7,NMC811,gASVMwIAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Li/Li+
8,NVP,gASVMzYAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
9,NVPF,gASVMicAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
10,Prussian White,gASVHBoAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+

In [20]:
db.get_cathode_materials(most_recent=True)

,name,object,date,version,reference
0,LFP,gASVURYAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Li/Li+
1,NaNiMn P2-O3 Composite,gASVay8AAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
2,NFM111 (Vendor A),gASVHyYAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
3,NFM111 (Vendor B),gASVLyIAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
4,NFM111 (Vendor C),gASVPgIAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
5,NFPP,gASVgi4AAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
6,NMC622,gASV9B4AAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Li/Li+
7,NMC811,gASVMwIAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Li/Li+
8,NVP,gASVMzYAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
9,NVPF,gASVMicAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+
10,Prussian White,gASVHBoAAAAAAACML3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,2025-11-26 16:03:11,0.1.16,Na/Na+