In [1]:
from steer_core.DataManager import DataManager
from steer_materials.CellMaterials.Base import CurrentCollectorMaterial
from steer_opencell_design import __version__

from datetime import datetime as dt
import pandas as pd

In [2]:
db = DataManager()

In [3]:
db.get_table_names()

['cells',
 'current_collector_materials',
 'insulation_materials',
 'separator_materials',
 'anode_materials',
 'binder_materials',
 'cathode_materials',
 'conductive_additive_materials']

In [4]:
db.drop_table('current_collector_materials')

In [5]:
db.create_table(table_name='current_collector_materials', columns={
    'name': 'TEXT',
    'object': 'TEXT',
    'date': 'TEXT',
    'version': 'TEXT'
})

In [6]:
# materials 

aluminum = CurrentCollectorMaterial(
    name='Aluminum', 
    density=2.70, 
    specific_cost=12.3, 
    color='#C0C0C0'
)

copper = CurrentCollectorMaterial(
    name='Copper', 
    density=8.96, 
    specific_cost=18.1, 
    color='#B87333'
)

materials = [aluminum, copper]
pickled_materials = [m.serialize() for m in materials]

In [7]:
aluminum.specific_cost_range

(6.15, 24.6)

In [8]:
# store data for current collectors

db.insert_data(table_name='current_collector_materials', data=pd.DataFrame({
    'name': [m.name for m in materials],
    'object': pickled_materials,
    'date': [m.last_updated for m in materials],
    'version': [__version__ for m in materials],
}))

In [9]:
db.get_current_collector_materials(most_recent=False)

,name,object,date,version
0,Aluminum,gASVKAEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-10-08 09:54:00,0.3.10
1,Copper,gASVJgEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-10-08 09:54:00,0.3.10

In [10]:
db.get_current_collector_materials()

,name,object,date,version
0,Aluminum,gASVKAEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-10-08 09:54:00,0.3.10
1,Copper,gASVJgEAAAAAAACMInN0ZWVyX21hdGVyaWFscy5DZWxsTW...,2025-10-08 09:54:00,0.3.10